### ISSUE TITLE
Gradle 5 instead of Gradle 6?

### ISSUE THREAD

**Issue by ghost** [Earthcomputer/MinecraftDev#14]
* Minecraft Development for IntelliJ plugin version: 1.3.2-earth.23
* IntelliJ version: 2020.1
* Operating System (this has come up enough times to be important): Window
When I make a new Fabric mod for 1.16-prerelease 8, it downloads Gradle 5.3.5 instead of Gradle 6. Shouldn't it download Gradle 6 instead? The loader version is 0.8.8-build.202 and the Loom version is 0.4-SNAPSHOT.

**Comment by Earthcomputer** [comment]
Thanks for your report! This issue will be addressed in the upstream version: https://github.com/minecraft-dev/MinecraftDev/pull/733
