### ISSUE TITLE
fabric.mod.json generated incorrectly

### ISSUE THREAD

**Issue by dexman545** [Earthcomputer/MinecraftDev#3]
Idea 2019.3
1.3.2-earth.23

Places "20w11a" in version instead of the proper semver "1.16-alpha.20.11.a"
Places trailing comma after minecraft:20w11a (quotations omitted)
Places minecraft:20w11a on same line as fabric:* (quotations omitted)

**Comment by Earthcomputer** [comment]
Thanks for your report! This issue will be addressed in the upstream version: https://github.com/minecraft-dev/MinecraftDev/pull/733
