### ISSUE TITLE
/usr/lib/python3.8 is a directory

### ISSUE THREAD

**Issue by nnym** [Earthcomputer/MinecraftDev#6]
Minecraft Development version: 2020.1-1.3.2-earth.23
IntelliJ IDEA version: 2020.1
operating system: Ubuntu

This issue occurs when I have any project open. 

[stack trace](https://gist.githubusercontent.com/transfarmer/bdbb9a0059608cafea4c89489270ab32/raw/4592ec39acdc366ea699d2040984af7d14587f75/stacktrace)

**Comment by Earthcomputer** [comment]
Thanks for your report! This issue will be addressed in the upstream version: https://github.com/minecraft-dev/MinecraftDev/pull/733
