### ISSUE TITLE
Access widener helpers

### ISSUE THREAD

**Issue by ramidzkh** [Earthcomputer/MinecraftDev#7]
Since Fabric now supports access wideners, it would be very helpful to add a few features
* Highlight access widener files and allow for jumping to the reference
* Detect unused access widener entries
* Error if a method is made accessible but not extendable, but it is being extended
* Warn in the fabric.mod.json if the access widener is not linked
* Add a ribbon/balloon to reload Gradle when the access widener changes

**Comment by Earthcomputer** [comment]
Thank you for your report! This issue has been transferred upstream and will be fixed there https://github.com/minecraft-dev/MinecraftDev/issues/737
