### ISSUE TITLE
Created project directory blank

### ISSUE THREAD

**Issue by kotx** [Earthcomputer/MinecraftDev#8]
Please include the following information in all bug reports:

* Minecraft Development for IntelliJ plugin version
2020.1-1.3.2-earth.23
* IntelliJ version
2020.1
* Operating System (this has come up enough times to be important)
Windows 10 64-bit

Creating a fabric mod via the wizard produces a project with nothing in the src/main/java and src/main/resources folders. They're just empty. Using OpenJDK 14 with OpenJ9.. Form fields: ![screenshot](https://awau.moe/3Qy7bZ4.png)
Don't know how to get the logs. Event log has nothing.

**Comment by kotx** [comment]
Using OpenJDK 8 did not fix the issue either. Directories are still blank.

**Comment by kotx** [comment]
.gradle/loom-cache and .gradle/buildOutputCleanup exist, however. The buildOutputCleanup.lock exists. build/loom-cache is empty.

**Comment by kotx** [comment]
Ah, I had to wait for it to decompile Minecraft. Takes a long time on my machine.

**Comment by maradotwebp** [comment]
how can I see the progress on decompiling? I've been waiting for over two hours now, but no files are showing up.

**Comment by kotx** [comment]
@froehlichA Sometimes switching the loom version to 0.2.7-SNAPSHOT fixes it. Sometimes it doesn't. I have no idea what causes this.

**Comment by maradotwebp** [comment]
Yeah, apparently upon project creation the autoselected loom version is 0.2.6-SNAPSHOT. The newest loom version is 0.4.31, which correctly generates all the files.
