### ISSUE TITLE
Button to add a mixin to the client mixin config

### ISSUE THREAD

**Issue by coderbot16** [Earthcomputer/MinecraftDev#9]
When a `@Mixin` isn't in any mixin config, a warning is generated, but the only suggestion is to add it to the `"mixins": []`part of the mixin config. However, it would be nice to be able to add the mixins to `"client": []` within the mixin config instead through that dialog:

```json
{
  "required": true,
  "minVersion": "0.8",
  "package": "net.fabricmc.example.mixin",
  "compatibilityLevel": "JAVA_8",
  "mixins": [
    (added here by default)
  ],
  "client": [
    (but I want to add it here)
  ],
  "injectors": {
    "defaultRequire": 1
  }
}
```

**Comment by Earthcomputer** [comment]
It adds it to the client if you add `@Environment(EnvType.CLIENT)` to the mixin

**Comment by UpcraftLP** [comment]
> It adds it to the client if you add `@Environment(EnvType.CLIENT)` to the mixin

Imo it should also add it to the client section if the mixin target class is client-only.

**Comment by Earthcomputer** [comment]
Thank you for your report! This issue has been transferred upstream and will be fixed there https://github.com/minecraft-dev/MinecraftDev/issues/736.
